/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark"))
    api(project(":flexmark-ext-abbreviation"))
    api(project(":flexmark-ext-anchorlink"))
    api(project(":flexmark-ext-aside"))
    api(project(":flexmark-ext-autolink"))
    api(project(":flexmark-ext-definition"))
    api(project(":flexmark-ext-emoji"))
    api(project(":flexmark-ext-escaped-character"))
    api(project(":flexmark-ext-footnotes"))
    api(project(":flexmark-ext-gfm-strikethrough"))
    api(project(":flexmark-ext-gfm-tasklist"))
    api(project(":flexmark-ext-ins"))
    api(project(":flexmark-ext-jekyll-front-matter"))
    api(project(":flexmark-ext-superscript"))
    api(project(":flexmark-ext-tables"))
    api(project(":flexmark-ext-toc"))
    api(project(":flexmark-ext-typographic"))
    api(project(":flexmark-ext-wikilink"))
    api(project(":flexmark-util-ast"))
    api(project(":flexmark-util-data"))
    api(project(":flexmark-util-misc"))
    api(project(":flexmark-util-sequence"))
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-core-test"))
    testImplementation(libs.org.pegdown.pegdown)
}

description = "flexmark-java pegdown profile"
