/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark"))
    api(libs.org.jsoup.jsoup)
    api(libs.com.ibm.icu.icu4j)
    api(libs.com.openhtmltopdf.openhtmltopdf.core)
    api(libs.com.openhtmltopdf.openhtmltopdf.pdfbox)
    api(libs.com.openhtmltopdf.openhtmltopdf.rtl.support)
    testImplementation(project(":flexmark-test-util"))
}

description = "flexmark-java extension for markdown to pdf conversion"
