/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark"))
    api(libs.org.nibor.autolink.autolink)
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-core-test"))
    testImplementation(project(":flexmark-ext-typographic"))
}

description = "flexmark-java extension for autolinking"
