/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark"))
    api(project(":flexmark-util"))
    api(project(":flexmark-test-util"))
    api(project(":flexmark-test-specs"))
    testImplementation(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.openjdk.jmh.jmh.generator.annprocess)
}

description = "shared test classes and core tests"
