/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-test-util"))
    api(libs.org.jetbrains.annotations)
}

description = "flexmark-java test spec files"
