/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark-ext-autolink"))
    api(project(":flexmark"))
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-core-test"))
    testImplementation(project(":flexmark-ext-typographic"))
    testImplementation(project(":flexmark-ext-ins"))
    testImplementation(project(":flexmark-ext-escaped-character"))
    testImplementation(project(":flexmark-ext-gfm-strikethrough"))
    testImplementation(project(":flexmark-ext-superscript"))
}

description = "flexmark-java extension for abbreviations in text"
