/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark"))
    api(project(":flexmark-ext-abbreviation"))
    api(project(":flexmark-ext-admonition"))
    api(project(":flexmark-ext-anchorlink"))
    api(project(":flexmark-ext-aside"))
    api(project(":flexmark-ext-attributes"))
    api(project(":flexmark-ext-autolink"))
    api(project(":flexmark-ext-definition"))
    api(project(":flexmark-ext-emoji"))
    api(project(":flexmark-ext-enumerated-reference"))
    api(project(":flexmark-ext-escaped-character"))
    api(project(":flexmark-ext-footnotes"))
    api(project(":flexmark-ext-gfm-issues"))
    api(project(":flexmark-ext-gfm-strikethrough"))
    api(project(":flexmark-ext-gfm-tasklist"))
    api(project(":flexmark-ext-gfm-users"))
    api(project(":flexmark-ext-gitlab"))
    api(project(":flexmark-ext-jekyll-front-matter"))
    api(project(":flexmark-ext-jekyll-tag"))
    api(project(":flexmark-ext-media-tags"))
    api(project(":flexmark-ext-resizable-image"))
    api(project(":flexmark-ext-macros"))
    api(project(":flexmark-ext-ins"))
    api(project(":flexmark-ext-xwiki-macros"))
    api(project(":flexmark-ext-superscript"))
    api(project(":flexmark-ext-tables"))
    api(project(":flexmark-ext-toc"))
    api(project(":flexmark-ext-typographic"))
    api(project(":flexmark-ext-wikilink"))
    api(project(":flexmark-ext-yaml-front-matter"))
    api(project(":flexmark-ext-youtube-embedded"))
    api(project(":flexmark-html2md-converter"))
    api(project(":flexmark-jira-converter"))
    api(project(":flexmark-pdf-converter"))
    api(project(":flexmark-profile-pegdown"))
    api(project(":flexmark-util-ast"))
    api(project(":flexmark-util-builder"))
    api(project(":flexmark-util-collection"))
    api(project(":flexmark-util-data"))
    api(project(":flexmark-util-dependency"))
    api(project(":flexmark-util-format"))
    api(project(":flexmark-util-html"))
    api(project(":flexmark-util-misc"))
    api(project(":flexmark-util-options"))
    api(project(":flexmark-util-sequence"))
    api(project(":flexmark-util-visitor"))
    api(project(":flexmark-youtrack-converter"))
}

description = "flexmark-all"
