/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark"))
    api(project(":flexmark-ext-gfm-strikethrough"))
    api(project(":flexmark-ext-tables"))
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-core-test"))
}

description = "flexmark-java extension for YouTrack conversion"
