/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util-misc"))
    api(project(":flexmark-util-data"))
    api(project(":flexmark-util-ast"))
    api(project(":flexmark-util-format"))
    api(project(":flexmark-util-sequence"))
    api(libs.junit.junit)
    api(libs.org.jetbrains.annotations)
}

description = "flexmark-java test utilities"
