/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark"))
    api(project(":flexmark-ext-emoji"))
    api(libs.org.jsoup.jsoup)
    testImplementation(project(":flexmark-test-util"))
}

description = "flexmark-java HTML to Markdown extensible converter"
