/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.annotations)
    api(project(":flexmark-util-ast"))
    api(project(":flexmark-util-data"))
    api(project(":flexmark-util-collection"))
    api(libs.org.slf4j.slf4j.api)
    testImplementation(project(":flexmark-test-util"))
}

description = "flexmark-java library for recursive tree iteration"
