/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util-ast"))
    api(project(":flexmark-util-builder"))
    api(project(":flexmark-util-collection"))
    api(project(":flexmark-util-data"))
    api(project(":flexmark-util-dependency"))
    api(project(":flexmark-util-format"))
    api(project(":flexmark-util-html"))
    api(project(":flexmark-util-misc"))
    api(project(":flexmark-util-sequence"))
    api(project(":flexmark-util-visitor"))
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-test-specs"))
    testImplementation(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.openjdk.jmh.jmh.generator.annprocess)
    testImplementation(libs.org.apache.logging.log4j.log4j.api)
    testImplementation(libs.org.apache.logging.log4j.log4j.core)
    testImplementation(libs.org.apache.logging.log4j.log4j.v1.v2.api)
}

description = "flexmark-java core"
