/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    testImplementation(project(":flexmark"))
    testImplementation(project(":flexmark-ext-autolink"))
    testImplementation(project(":flexmark-ext-abbreviation"))
    testImplementation(project(":flexmark-ext-emoji"))
    testImplementation(project(":flexmark-ext-footnotes"))
    testImplementation(project(":flexmark-ext-gfm-strikethrough"))
    testImplementation(project(":flexmark-ext-gfm-tasklist"))
    testImplementation(project(":flexmark-ext-tables"))
    testImplementation(project(":flexmark-ext-toc"))
    testImplementation(project(":flexmark-ext-yaml-front-matter"))
    testImplementation(project(":flexmark-ext-wikilink"))
    testImplementation(libs.org.pegdown.pegdown)
    testImplementation(project(":flexmark-test-util"))
    testImplementation(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.openjdk.jmh.jmh.generator.annprocess)
    testImplementation(project(":flexmark-core-test"))
    testImplementation(project(":flexmark-test-specs"))
}

description = "flexmark-java integration tests"
