/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":flexmark-util"))
    api(project(":flexmark"))
    testImplementation(project(":flexmark-test-util"))
    testImplementation(project(":flexmark-ext-anchorlink"))
    testImplementation(project(":flexmark-ext-toc"))
    testImplementation(project(":flexmark-ext-definition"))
    testImplementation(project(":flexmark-ext-escaped-character"))
    testImplementation(project(":flexmark-ext-tables"))
    testImplementation(project(":flexmark-ext-typographic"))
    testImplementation(project(":flexmark-ext-emoji"))
    testImplementation(project(":flexmark-core-test"))
}

description = "flexmark-java extension for attributes"
